---

- name: Generic install for mat servers
  hosts:
    - "*.mat.stacken.kth.se"
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
      loop:
        - fail2ban
        - heimdal-clients
        - tmux
        - screen
        - emacs
        - neovim
        - sharutils
        - collectd-core

    - name: Deploy sshkeys from GH
      authorized_key:
        user: root
        key: "https://github.com/{{ item }}.keys"
        comment: "GitHub user {{ item }}"
      loop:
        - nsg
        - fabstr
        - kaj

    - name: Enable GSSAPIAuthentication=yes
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?GSSAPIAuthentication"
        line: "GSSAPIAuthentication yes"

    - name: Enable GSSAPIKeyExchange=yes
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?GSSAPIKeyExchange"
        line: "GSSAPIKeyExchange yes"

    - name: Enable GSSAPICleanupCredentials=no
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?GSSAPICleanupCredentials"
        line: "GSSAPICleanupCredentials no"

    - name: Enable GSSAPIStrictAcceptorCheck=no
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?GSSAPIStrictAcceptorCheck"
        line: "GSSAPIStrictAcceptorCheck no"

    - name: Enable KerberosAuthentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?KerberosAuthentication"
        line: "KerberosAuthentication yes"

    - name: Enable KerberosOrLocalPasswd
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?KerberosOrLocalPasswd"
        line: "KerberosOrLocalPasswd yes"

    - name: Enable KerberosTicketCleanup
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?KerberosTicketCleanup"
        line: "KerberosTicketCleanup yes"

    - name: Update k5login
      lineinfile:
        dest: /root/.k5login
        regexp: "^{{ item }}.root"
        line: "{{ item }}/root@STACKEN.KTH.SE"
        create: yes
      loop:
        - nsg
        - fabian
        - kaj

    - name: Deploy collectd.conf file
      template:
        src: templates/collectd.conf.j2
        dest: /etc/collectd/collectd.conf

    - name: Enable and start collectd
      service:
        name: collectd
        state: restarted
        enabled: yes
