---

- name: Generic install for mat servers
  hosts:
    - "*.mat.stacken.kth.se"
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
      loop:
        - fail2ban
        - heimdal-clients
        - tmux
        - screen
        - emacs
        - neovim
        - sharutils
        - collectd-core

    - name: Deploy sshkeys from GH
      authorized_key:
        user: root
        key: "https://github.com/{{ item }}.keys"
        comment: "GitHub user {{ item }}"
      loop:
        - nsg
        - fabstr
        - kaj

    - include_tasks: krb.yml

    - name: Deploy collectd.conf file
      template:
        src: templates/collectd.conf.j2
        dest: /etc/collectd/collectd.conf

    - name: Enable and start collectd
      service:
        name: collectd
        state: restarted
        enabled: yes

- import_playbook: kvm.yml
