---

- name: Generic install for mat servers
  hosts:
    - "*.mat.stacken.kth.se"
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
      loop:
        - fail2ban
        - heimdal-clients
        - tmux
        - screen
        - emacs
        - neovim
        - sharutils

    - name: Deploy sshkeys from GH
      authorized_key:
        user: root
        key: "https://github.com/{{ item }}.keys"
        comment: "GitHub user {{ item }}"
      loop:
        - nsg
        - fabstr
        - kaj
